version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper

  game-management-service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-init-scripts/1-db.sql:/docker-entrypoint-initdb.d/1-db.sql

  game-management-service:
    build:
      context: game-management-service
      dockerfile: Dockerfile
    command: java -jar /home/game-management-service.jar
    ports:
      - 8080:8080
    depends_on:
      - game-management-service-db
      - kafka
    environment:
      - spring.datasource.url=jdbc:postgresql://game-management-service-db:5432/gms
      - spring.kafka.bootstrap-servers=kafka:9092

  player-service-instance-1:
    build:
      context: player-service
      dockerfile: Dockerfile
    command: java -jar /home/player-service.jar
    ports:
      - 8081:8080
    depends_on:
      - kafka
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - player.game-action-event.topic=game-action-22bec6bb-880c-492d-80d6-45411460ed6f
      - player.game-event.topic=game-22bec6bb-880c-492d-80d6-45411460ed6f

  player-service-instance-2:
    build:
      context: player-service
      dockerfile: Dockerfile
    command: java -jar /home/player-service.jar
    ports:
      - 8082:8080
    depends_on:
      - kafka
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - player.game-action-event.topic=game-action-a10da818-6c54-4b91-9271-a16da1eac539
      - player.game-event.topic=game-a10da818-6c54-4b91-9271-a16da1eac539
